### ISSUE TITLE
Tracers on model start

### ISSUE THREAD

**Issue by sabinz** [EarthByte/citcoms#9]
Model with tracers will not go past initialisation as there is some mismatch in tracer numbers.

In my local copy, I just comment out the line in:
/src/lib/lib/Tracer_setup.c 
exit call on Line 1041 to be comment out

Should we do the same in here, or somehow deal with the issue?

**Comment by djbower** [comment]
@sabinz  In the last commit (b946e86) this problem is fixed.  You will need to 'git pull' to get the latest changes and then recompile and make.
